export const ITEM_CREATE_REQ = 'ITEM_CREATE_REQ';
export const ITEM_CREATE_RES = 'ITEM_CREATE_RES';
export const ITEM_UPDATE_REQ = 'ITEM_UPDATE_REQ';
export const ITEM_UPDATE_RES = 'ITEM_UPDATE_RES';
export const USER_CREATE_REQ = 'USER_CREATE_REQ';
export const USER_CREATE_RES = 'USER_CREATE_RES';
