#!/bin/zsh

function start_app {
	local response
	trap 'false' INT ZERROR
	while true
	do
		read -t 5 response?'Type exit <enter> to exit testing script.' || :
		if [[ $response == "exit" ]] break
		node app.js
	done
}


mongod --dbpath ./data/db &
local mongo_ip=$!
sleep 2s
start_app

kill $mongo_ip

